import '../assets/css/bootstrap.min.css'
import '../assets/css/fontawesome.min.css'
import '../assets/css/hover-min.css'
import '../assets/css/style.css'
import '../assets/css/toastr.min.css'
import '../assets/css/jquery-confirm.min.css'
import '../assets/slick/slick.css'
import '../assets/fonts/fontstyle.css'

import '../assets/js/all.min.js'
import '../assets/js/jquery.min.js'
import '../assets/js/popper.min.js'
import '../assets/js/bootstrap.min.js'
import '../assets/slick/slick.js'
import '../assets/js/main.js'
import '../assets/js/jquery-confirm.min.js'